[project]
name = "zostel-finder"
version = "0.1.0"
description = "Find available Zostel properties in a timerange!"
readme = "readme.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "streamlit>=1.39.0",
]
